#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

SOURCE_PATH="$(dirname $0)/.."
COMMIT_SHA="$(git --git-dir ${SOURCE_PATH}/.git rev-parse HEAD)"

printf "> Building component with version ${EFFECTIVE_VERSION} - ${COMMIT_SHA}\n"

CA_PATH="$(mktemp -d)"
cp ${BASE_DEFINITION_PATH} "${CA_PATH}/component-descriptor.yaml"

printf "> Create Component Archive\n"


if [ -z "$RESOURCES_FILE_PATH" ]; then
  component-cli ca "${CA_PATH}" "${CTF_PATH}" VERSION=${EFFECTIVE_VERSION}
else
  component-cli ca "${CA_PATH}" "${CTF_PATH}" -r ${RESOURCES_FILE_PATH} VERSION=${EFFECTIVE_VERSION}
fi

